/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Echo_H
#define Echo_H

#include <TProcessor.h>
#include "echo_types.h"

namespace echo_thrift {

class EchoIf {
 public:
  virtual ~EchoIf() {}
  virtual void Echo(EchoData& _return, const std::string& echo_data) = 0;
};

class EchoIfFactory {
 public:
  typedef EchoIf Handler;

  virtual ~EchoIfFactory() {}

  virtual EchoIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(EchoIf* /* handler */) = 0;
};

class EchoIfSingletonFactory : virtual public EchoIfFactory {
 public:
  EchoIfSingletonFactory(const boost::shared_ptr<EchoIf>& iface) : iface_(iface) {}
  virtual ~EchoIfSingletonFactory() {}

  virtual EchoIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(EchoIf* /* handler */) {}

 protected:
  boost::shared_ptr<EchoIf> iface_;
};

class EchoNull : virtual public EchoIf {
 public:
  virtual ~EchoNull() {}
  void Echo(EchoData& /* _return */, const std::string& /* echo_data */) {
    return;
  }
};

typedef struct _Echo_Echo_args__isset {
  _Echo_Echo_args__isset() : echo_data(false) {}
  bool echo_data;
} _Echo_Echo_args__isset;

class Echo_Echo_args {
 public:

  Echo_Echo_args() : echo_data("") {
  }

  virtual ~Echo_Echo_args() throw() {}

  std::string echo_data;

  _Echo_Echo_args__isset __isset;

  void __set_echo_data(const std::string& val) {
    echo_data = val;
  }

  bool operator == (const Echo_Echo_args & rhs) const
  {
    if (!(echo_data == rhs.echo_data))
      return false;
    return true;
  }
  bool operator != (const Echo_Echo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Echo_Echo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Echo_Echo_pargs {
 public:


  virtual ~Echo_Echo_pargs() throw() {}

  const std::string* echo_data;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Echo_Echo_result__isset {
  _Echo_Echo_result__isset() : success(false) {}
  bool success;
} _Echo_Echo_result__isset;

class Echo_Echo_result {
 public:

  Echo_Echo_result() {
  }

  virtual ~Echo_Echo_result() throw() {}

  EchoData success;

  _Echo_Echo_result__isset __isset;

  void __set_success(const EchoData& val) {
    success = val;
  }

  bool operator == (const Echo_Echo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Echo_Echo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Echo_Echo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Echo_Echo_presult__isset {
  _Echo_Echo_presult__isset() : success(false) {}
  bool success;
} _Echo_Echo_presult__isset;

class Echo_Echo_presult {
 public:


  virtual ~Echo_Echo_presult() throw() {}

  EchoData* success;

  _Echo_Echo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class EchoClient : virtual public EchoIf {
 public:
  EchoClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  EchoClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Echo(EchoData& _return, const std::string& echo_data);
  void send_Echo(const std::string& echo_data);
  void recv_Echo(EchoData& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class EchoProcessor : public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<EchoIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (EchoProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_Echo(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  EchoProcessor(boost::shared_ptr<EchoIf> iface) :
    iface_(iface) {
    processMap_["Echo"] = &EchoProcessor::process_Echo;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~EchoProcessor() {}
};

class EchoProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  EchoProcessorFactory(const ::boost::shared_ptr< EchoIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< EchoIfFactory > handlerFactory_;
};

class EchoMultiface : virtual public EchoIf {
 public:
  EchoMultiface(std::vector<boost::shared_ptr<EchoIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~EchoMultiface() {}
 protected:
  std::vector<boost::shared_ptr<EchoIf> > ifaces_;
  EchoMultiface() {}
  void add(boost::shared_ptr<EchoIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Echo(EchoData& _return, const std::string& echo_data) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->Echo(_return, echo_data);
        return;
      } else {
        ifaces_[i]->Echo(_return, echo_data);
      }
    }
  }

};

} // namespace

#endif
